#!/bin/sh
# Build-time installer for the storage-tuning dev container Feature.
# Runs as root inside the image being built. Nothing here touches the host;
# the host-side work happens at postStartCommand via storage-tuning.sh.
set -eu

# Feature options (uppercased by the devcontainer CLI) with their defaults.
DOCKERSOCKET="${DOCKERSOCKET:-/var/run/docker-host.sock}"
HELPERIMAGE="${HELPERIMAGE:-}"
WARMREADERS="${WARMREADERS:-2}"
VERBOSE="${VERBOSE:-false}"
TIMEOUTSECONDS="${TIMEOUTSECONDS:-900}"

SRC=$(cd "$(dirname "$0")" && pwd)
DEST=/usr/local/share/storage-tuning

check_safe() {
    # Values are written into a shell file; refuse anything that would need quoting.
    case "$2" in
        *[!A-Za-z0-9_.:/@+-]*)
            echo "storage-tuning: option $1 has unsupported characters: '$2'" >&2
            exit 1 ;;
    esac
}
check_int() {
    case "$2" in
        ''|*[!0-9]*) echo "storage-tuning: option $1 must be a non-negative integer, got '$2'" >&2; exit 1 ;;
    esac
}

check_safe dockerSocket "$DOCKERSOCKET"
check_safe helperImage "$HELPERIMAGE"
check_int warmReaders "$WARMREADERS"
check_int timeoutSeconds "$TIMEOUTSECONDS"
case "$VERBOSE" in true|false) ;; *) echo "storage-tuning: option verbose must be true or false" >&2; exit 1 ;; esac

mkdir -p "$DEST"
install -m 0755 "$SRC/apply-tunables.py" "$DEST/apply-tunables.py"
install -m 0755 "$SRC/run-on-host.py" "$DEST/run-on-host.py"
install -m 0755 "$SRC/storage-tuning.sh" "$DEST/storage-tuning"
ln -sf "$DEST/storage-tuning" /usr/local/bin/storage-tuning

# Defaults only: the environment at run time takes precedence.
cat > "$DEST/config.env" <<EOF
# Generated by the storage-tuning Feature installer from its options.
: "\${STORAGE_TUNING_DOCKER_SOCKET:=$DOCKERSOCKET}"
: "\${STORAGE_TUNING_HELPER_IMAGE:=$HELPERIMAGE}"
: "\${STORAGE_TUNING_WARM_READERS:=$WARMREADERS}"
: "\${STORAGE_TUNING_VERBOSE:=$VERBOSE}"
: "\${STORAGE_TUNING_TIMEOUT:=$TIMEOUTSECONDS}"
EOF
chmod 0644 "$DEST/config.env"

# The wrapper needs a POSIX sh and python3: run-on-host.py speaks the Docker
# Engine API over the bind-mounted host socket itself, so no docker CLI (and no
# docker-outside-of-docker Feature) is required. Debian/Ubuntu images without
# python3 get it installed here; elsewhere the wrapper logs and exits 0 at run time.
if ! command -v python3 >/dev/null 2>&1; then
    if command -v apt-get >/dev/null 2>&1; then
        echo "storage-tuning: python3 not found; installing it"
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y --no-install-recommends python3
        rm -rf /var/lib/apt/lists/*
    else
        echo "storage-tuning: warning: python3 not found and no apt-get; the postStart hook will be a no-op" >&2
    fi
fi

echo "storage-tuning: installed to $DEST (docker socket $DOCKERSOCKET, warm readers $WARMREADERS, timeout ${TIMEOUTSECONDS}s)"
echo "storage-tuning: opt in with the ENABLE_STORAGE_TUNING / ENABLE_STORAGE_PREWARM secrets"
